### PR TITLE
Support for the report command.

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
register, challenge, accept, lost... too many commands.

We should should be able to, on a whim, say:

`pongbot report @opponent 11:0, 2:11, 13:15`

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
oops, this was meant for my own repo

**Comment by dblock** [comment]
Gamebot supports `lost to @opponent` without a challenge. Registration is still required, but that's something that could actually become automatic with a mention with a bit of work.

**Comment by NullVoxPopuli** [comment]
That's good news!

I'll use that for report. Cause I want the winner to be able to report as
well.

**Comment by dblock** [comment]
We didn't want winners to be able to report because people can easily abuse of it to grow their elo. Anyone cam DM the bot and you wouldn't even know they did it.

**Pull request closed without merging**
